DROP DATABASE IF EXISTS HLIN511;
CREATE DATABASE HLIN511;
DROP TABLE IF EXISTS VISITEUR;
DROP TABLE IF EXISTS EVENEMENT;

CREATE TABLE CONTRIBUTEUR( 
ID_CONTRIBUTEUR INT NOT NULL,
ID_EV INT,
NOM_CONTRIB VARCHAR(50),
PRENOM_CONTRIB VARCHAR(50),
CONSTRAINT PK_CONTRIBUTEUR PRIMARY KEY (ID_CONTRIBUTEUR)
);

CREATE TABLE EVENEMENT(
ID_EV INT NOT NULL AUTO_INCREMENT,
ID_CONTRIB INT,
LOCALISATION VARCHAR(100),
THEME VARCHAR(100),
DATE_EV DATE,
DESCRIPTION TEXT,
EFFECTIF_MIN INT,
EFFECTIF_MAX INT,
NOTE INT, 
CONSTRAINT PK_EVENT PRIMARY KEY (ID_EV), 
CONSTRAINT FK_CONTRIBUTEUR FOREIGN KEY (ID_CONTRIB) REFERENCES CONTRIBUTEUR(ID_CONTRIBUTEUR)
);

CREATE TABLE VISITEUR (
ID_VISITEUR INT NOT NULL,
ID_EV INT,
NOM_VISITEUR VARCHAR(50),
PRENOM_VISITEUR VARCHAR(50),
CONSTRAINT PK_VISITEUR PRIMARY KEY (ID_VISITEUR),
CONSTRAINT FK_EVENT FOREIGN KEY (ID_EV) REFERENCES EVENEMENT(ID_EV)
);


CREATE TABLE ADMINISTRATEUR (
ID_ADMIN INT NOT NULL,
ID_CONTRIBUTEUR INT NOT NULL,
NOM_ADMIN VARCHAR(50),
PRENOM_ADMIN VARCHAR(50),
CONSTRAINT PK_ADMIN PRIMARY KEY (ID_ADMIN),
CONSTRAINT FK_ADMIN FOREIGN KEY (ID_CONTRIBUTEUR) REFERENCES CONTRIBUTEUR(ID_CONTRIBUTEUR)
);

INSERT INTO EVENEMENT (LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('Montpellier','Historique','2019-10-20','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('Nimes','Historique','2019-2-12','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('Lunel','Historique','2019-9-9','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('Lattes','Historique','2019-12-20','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('Perol','Historique','2019-1-20','Une fete historique',10,100,NULL);


