/*Nom des visiteurs des evenements historiques de montpellier*/
SELECT NOM_VISITEUR
FROM VISITEUR VIS, EVENEMENT EV, VISITE
WHERE VIS.ID_VISITEUR = VISITE.ID_VISITEUR
AND EV.ID_EV = VISITE.ID_EV
AND EV.LOCALISATION = 'MONTPELLIER';

/*JOIN de visiteurs et evenements*/
SELECT *
FROM VISITEUR VIS, EVENEMENT EV, VISITE
WHERE VIS.ID_VISITEUR = VISITE.ID_VISITEUR
AND EV.ID_EV = VISITE.ID_EV;

/*JOIN V2*/
SELECT *
FROM VISITE
JOIN VISITEUR ON VISITEUR.ID_VISITEUR = VISITE.ID_VISITEUR
JOIN  EVENEMENT ON EVENEMENT.ID_EV = VISITE.ID_EV;

/*Les visiteurs de la fete0*/
SELECT VISITE.ID_VISITEUR, NOM_VISITEUR
FROM VISITE, VISITEUR, EVENEMENT EV
WHERE VISITEUR.ID_VISITEUR = VISITE.ID_VISITEUR
AND EV.ID_EV = VISITE.ID_EV
AND EV.NOM = 'la fete0';


/*Liste des ADMINS*/
SELECT *
FROM CONTRIBUTEUR, ADMINISTRATEUR
WHERE CONTRIBUTEUR.ID_CONTRIBUTEUR = ADMINISTRATEUR.ID_CONTRIBUTEUR;
