/*
DROP DATABASE IF EXISTS HLIN511;
CREATE DATABASE HLIN511;
*/

/*NE PAS CHANGER L'ORDRE*/
DROP TABLE IF EXISTS VISITE;
DROP TABLE IF EXISTS VISITEUR;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS ADMINISTRATEUR;
DROP TABLE IF EXISTS CONTRIBUTEUR;



CREATE TABLE CONTRIBUTEUR(
ID_CONTRIBUTEUR INT NOT NULL AUTO_INCREMENT,
NOM_CONTRIB VARCHAR(50),
PRENOM_CONTRIB VARCHAR(50),
CONSTRAINT PK_CONTRIBUTEUR PRIMARY KEY (ID_CONTRIBUTEUR)
);

CREATE TABLE EVENEMENT(
ID_EV INT NOT NULL AUTO_INCREMENT,
ID_CONTRIB INT,
NOM NVARCHAR(200),
LOCALISATION VARCHAR(100),
THEME VARCHAR(100),
DATE_EV DATE,
DESCRIPTION TEXT,
EFFECTIF_MIN INT,
EFFECTIF_MAX INT,
NOTE INT,
CONSTRAINT PK_EVENT PRIMARY KEY (ID_EV),
CONSTRAINT FK_CONTRIBUTEUR FOREIGN KEY (ID_CONTRIB) REFERENCES CONTRIBUTEUR(ID_CONTRIBUTEUR)
);

CREATE TABLE VISITEUR (
ID_VISITEUR INT NOT NULL AUTO_INCREMENT,
NOM_VISITEUR VARCHAR(50),
PRENOM_VISITEUR VARCHAR(50),
CONSTRAINT PK_VISITEUR PRIMARY KEY (ID_VISITEUR)
);

CREATE TABLE VISITE(
ID_VISITEUR INT NOT NULL,
ID_EV INT NOT NULL,
CONSTRAINT FK_VISITE_VISITEUR FOREIGN KEY (ID_VISITEUR) REFERENCES VISITEUR(ID_VISITEUR),
CONSTRAINT FK_VISITE_EVENT FOREIGN KEY (ID_EV) REFERENCES EVENEMENT(ID_EV)
);

CREATE TABLE ADMINISTRATEUR (
ID_CONTRIBUTEUR INT NOT NULL,
CONSTRAINT FK_ADMIN FOREIGN KEY (ID_CONTRIBUTEUR) REFERENCES CONTRIBUTEUR(ID_CONTRIBUTEUR)
);
/*==================================EVENEMENT===============================================*/
INSERT INTO EVENEMENT (NOM,LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('La fete0','Montpellier','Historique','2019-10-20','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (NOM,LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('La fete1','Nimes','Historique','2019-2-12','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (NOM,LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('La fete2','Lunel','Historique','2019-9-9','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (NOM,LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('La fete3','Lattes','Historique','2019-12-20','Une fete historique',10,100,NULL);

INSERT INTO EVENEMENT (NOM,LOCALISATION,THEME,DATE_EV,DESCRIPTION,EFFECTIF_MIN,EFFECTIF_MAX,NOTE)
  VALUES ('La fete4','Perol','Historique','2019-1-20','Une fete historique',10,100,NULL);

/*=================================VISITEURS================================================*/
INSERT INTO VISITEUR(PRENOM_VISITEUR,NOM_VISITEUR)
  VALUES ('Leif','HENRIKSEN');

INSERT INTO VISITEUR(PRENOM_VISITEUR,NOM_VISITEUR)
  VALUES ('Juan','LAREZ');

INSERT INTO VISITEUR(PRENOM_VISITEUR,NOM_VISITEUR)
  VALUES ('JEREMY','BOULANGER');

/*=================================VISITE==================================================*/

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'HENRIKSEN'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'Nimes'));

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'HENRIKSEN'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'Lattes'));

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'HENRIKSEN'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'Montpellier'));

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'BOULANGER'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'Lattes'));

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'BOULANGER'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'Nimes'));

INSERT INTO VISITE(ID_VISITEUR, ID_EV)
VALUES((SELECT ID_VISITEUR FROM VISITEUR WHERE NOM_VISITEUR = 'LAREZ'),
       (SELECT ID_EV FROM EVENEMENT WHERE THEME = 'Historique' AND LOCALISATION = 'MONTPELLIER'));

/*=============================CONTRIBUTEUR=================================================*/
INSERT INTO CONTRIBUTEUR (NOM_CONTRIB, PRENOM_CONTRIB)
VALUES ('HENRIKSEN', 'Leif');

INSERT INTO CONTRIBUTEUR (NOM_CONTRIB, PRENOM_CONTRIB)
VALUES ('CONTRIBUTEUR', 'Cont1');

/*=============================ADMIN=========================================================*/
INSERT INTO ADMINISTRATEUR(ID_CONTRIBUTEUR)
VALUES ((SELECT ID_CONTRIBUTEUR FROM CONTRIBUTEUR WHERE NOM_CONTRIB = 'HENRIKSEN'));
