/*
DROP DATABASE IF EXISTS HLIN511;
CREATE DATABASE HLIN511;
*/
DROP TABLE IF EXISTS VISITE;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS UTILISATEUR;


CREATE TABLE UTILISATEUR(
ID INT,
NOM VARCHAR(50),
PRENOM VARCHAR(50),
EMAIL VARCHAR (50),
MDP VARCHAR(50),
TYPE_UTILISATEUR INT,
ADRESSE VARCHAR(50),
AGE INT NOT NULL,
CONSTRAINT PK_UTILISATEURS PRIMARY KEY (ID),
CONSTRAINT DOM_EMAIL CHECK ( EMAIL LIKE '%@%'),
CONSTRAINT DOM_TYPE_UTILISATEUR CHECK  ( TYPE_UTILISATEUR BETWEEN 0 AND 2),
CONSTRAINT DOM_AGE CHECK (AGE > 0)
);

CREATE TABLE EVENEMENT (
ID_EVENT INT,
NOM_EVENT VARCHAR(50),
ADRESSE VARCHAR(50),
LONGITUDE FLOAT,
LATITUDE FLOAT,
THEME VARCHAR(20),
DATE_EV DATE,
DESCRIPTIF TEXT,
EFFECTIF_MAX INT,
EFFECTIF_MIN INT,
CONSTRAINT PK_EVENEMENT PRIMARY KEY (ID_EVENT),
CONSTRAINT DOM_GPS CHECK (LATITUDE >0 AND LONGITUDE >0),
CONSTRAINT DOM_EFFECTIF CHECK (EFFECTIF_MIN_MAX BETWEEN 1 AND 50)
);

CREATE TABLE VISITE(
ID_VISITEUR INT NOT NULL,
ID_EV INT NOT NULL,
CONSTRAINT FK_VISITE_VISITEUR FOREIGN KEY (ID_VISITEUR) REFERENCES UTILISATEUR(ID),
CONSTRAINT FK_VISITE_EVENT    FOREIGN KEY (ID_EV)       REFERENCES EVENEMENT(ID_EVENT)
);
