/*
DROP DATABASE IF EXISTS HLIN511;
CREATE DATABASE HLIN511;
*/  
DROP TABLE IF EXISTS VISITE;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS UTILISATEUR;


CREATE TABLE UTILISATEUR(
ID INT AUTO_INCREMENT,
NOM VARCHAR(50),
PRENOM VARCHAR(50),
EMAIL VARCHAR (50),
MDP VARCHAR(50),
TYPE_UTILISATEUR INT,
ADRESSE VARCHAR(50),
AGE INT NOT NULL,
CONSTRAINT PK_UTILISATEURS PRIMARY KEY (ID),
CONSTRAINT DOM_EMAIL CHECK ( EMAIL LIKE '%@%'),
CONSTRAINT DOM_TYPE_UTILISATEUR CHECK  ( TYPE_UTILISATEUR BETWEEN 0 AND 2),
CONSTRAINT DOM_AGE CHECK (AGE > 0)
);

CREATE TABLE EVENEMENT (
ID_EVENT INT AUTO_INCREMENT,
NOM_EVENT VARCHAR(50),
ADRESSE VARCHAR(50),
LONGITUDE FLOAT,
LATITUDE FLOAT,
THEME VARCHAR(20),
DATE_EV DATE,
DESCRIPTIF TEXT,
EFFECTIF_MAX INT,
EFFECTIF_MIN INT,
CONSTRAINT PK_EVENEMENT PRIMARY KEY (ID_EVENT),
CONSTRAINT DOM_GPS CHECK (LATITUDE >0 AND LONGITUDE >0)
);

CREATE TABLE VISITE(
ID_VISITEUR INT NOT NULL,
ID_EV INT NOT NULL,

CONSTRAINT FK_VISITE_VISITEUR FOREIGN KEY (ID_VISITEUR) REFERENCES UTILISATEUR(ID),
CONSTRAINT FK_VISITE_EVENT    FOREIGN KEY (ID_EV)       REFERENCES EVENEMENT(ID_EVENT),
CONSTRAINT PK_VISITE          PRIMARY KEY (ID_VISITEUR, ID_EV)
);

INSERT INTO EVENEMENT (NOM_EVENT, ADRESSE, LONGITUDE, LATITUDE, THEME, DATE_EV, DESCRIPTIF, EFFECTIF_MAX, EFFECTIF_MIN) VALUES ("Test","abc",52,45,"xyz","2019-10-5","test",20,60);
INSERT INTO EVENEMENT (NOM_EVENT, ADRESSE, LONGITUDE, LATITUDE, THEME, DATE_EV, DESCRIPTIF, EFFECTIF_MAX, EFFECTIF_MIN)VALUES ("Test","abc",52,45,"xyz","2019-10-5","test",20,60);
INSERT INTO EVENEMENT (NOM_EVENT, ADRESSE, LONGITUDE, LATITUDE, THEME, DATE_EV, DESCRIPTIF, EFFECTIF_MAX, EFFECTIF_MIN)VALUES ("Test","abc",52,45,"xyz","2019-10-5","test",20,60);
INSERT INTO EVENEMENT (NOM_EVENT, ADRESSE, LONGITUDE, LATITUDE, THEME, DATE_EV, DESCRIPTIF, EFFECTIF_MAX, EFFECTIF_MIN)VALUES ("Test","abc",52,45,"xyz","2019-10-5","test",20,60);


INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, MDP, TYPE_UTILISATEUR, ADRESSE, AGE) VALUES ('utilisateur', '', ' @', 'utilisateur', 0, '', 420);
INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, MDP, TYPE_UTILISATEUR, ADRESSE, AGE) VALUES ('admin', '', '@', 'admin', 1, '', 69);
INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, MDP, TYPE_UTILISATEUR, ADRESSE, AGE) VALUES ('contributeur', '', '@', 'contributeur', 2, '', 7);